FROM node:12-alpine

RUN apk update && apk upgrade
RUN echo "http://dl-2.alpinelinux.org/alpine/edge/main" > /etc/apk/repositories
RUN echo "http://dl-2.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
RUN echo "http://dl-2.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories

RUN apk -U --no-cache \
	--allow-untrusted add \
	zlib-dev \
	chromium \
	xvfb \
	nss \
	wait4ports \
	xorg-server \
	dbus \
	ttf-freefont \
	grep \
	udev \
	&& apk del --purge --force linux-headers binutils-gold gnupg zlib-dev libc-utils \
	&& rm -rf /var/lib/apt/lists/* \
	/var/cache/apk/* \
	/usr/share/man \
	/tmp/* \
	/usr/lib/node_modules/npm/man \
	/usr/lib/node_modules/npm/doc \
	/usr/lib/node_modules/npm/html \
	/usr/lib/node_modules/npm/scripts

WORKDIR /app/

COPY ./package*.json ./

RUN npm install -g pm2
RUN npm i

#RUN addgroup -S pptruser && adduser -S -g pptruser pptruser \
#    && mkdir -p /home/pptruser/Downloads /app \
#    && chown -R pptruser:pptruser /home/pptruser \
#    && chown -R pptruser:pptruser /app

# Run everything after as non-privileged user.
#USER pptruser

#RUN ls -laF /usr/bin/

EXPOSE 3000

#ENTRYPOINT [ "dumb-init", "--" ]
#CMD [ "pm2-runtime", "start", "ecosystem.config.js", "--env", "development" ]
ENTRYPOINT [ "pm2-runtime", "start", "ecosystem.config.js", "--env", "development" ]
